### ISSUE TITLE
Error in saving video during evaluation

### ISSUE THREAD

**Issue by vedantdave97** [gemcollector/RL-ViGen#10]
I changed the locodmc_eval.sh and added save_video=True in the script. It shows error while running, specifically:
```
  File "locodmc_eval.py", line 166, in main
    workspace.eval()
  File "/home/vedant/RL-ViGen/locodmc_eval.py", line 130, in eval
    self.video_recorder.save(f'{self.global_frame}.mp4')
  File "/home/vedant/RL-ViGen/video.py", line 40, in save
    imageio.mimsave(str(path), self.frames, fps=self.fps)
  File "/home/vedant/anaconda3/envs/rl-vigen/lib/python3.8/site-packages/imageio/core/functions.py", line 408, in mimwrite
    raise ValueError("Image is not numeric, but {}.".format(imt.__name__))
ValueError: Image is not numeric, but NoneType.
```

This arises due to the fact that all the frames during rendering from video i.e returns None. https://github.com/gemcollector/RL-ViGen/blob/0158cec6d0105856b5aff8021d9de6ba53c707ac/video.py#L34

FYI, I have done this additionally in locodmc_eval.py to enable video capture:
 https://github.com/gemcollector/RL-ViGen/blob/0158cec6d0105856b5aff8021d9de6ba53c707ac/video.py#L34
to
```
self.video_recorder =VideoRecorder(self.work_dir if self.cfg.save_video else None)
```

Am I missing here something?

**Comment by gemcollector** [comment]
Hi there,
I've made some updates to the `locodmc_eval.py`, specifically to the `record` function. I evaluated it on the local machine, but I haven't tested it directly in the repo yet. If there are still any issues, please don't hesitate to let me know. Thank you for pointing out the problem!

**Comment by vedantdave97** [comment]
Thanks for the update. I'll check it out and see if it works.

**Comment by vedantdave97** [comment]
The self.frames takes the first value as None and thus this line is failing.

https://github.com/gemcollector/RL-ViGen/blob/e5e02d2eae3d382f56b26c4f3a1d3ec0791cdacd/video.py#L53

A workaround would be just beginning from the second frame:
```
def save(self, file_name):
        if self.enabled:
            path = self.save_dir / file_name
            imageio.mimsave(str(path), self.frames[1:], fps=self.fps)
```

**Comment by gemcollector** [comment]
Thank you so much for bringing this to my attention! I had fixed that bug earlier but forgot to push the update. Please take a moment to check out the updated `video.py` in the repo. I sincerely apologize for any inconvenience this may have caused you!

**Comment by vedantdave97** [comment]
Works perfectly. Thanks for the update.
