### ISSUE TITLE
Cannot reproduce results from the original papers

### ISSUE THREAD

**Issue by vedantdave97** [gemcollector/RL-ViGen#11]
Hello @gemcollector 
I have been trying to reproduce SGQN and PIEG results for DMC. For SGQN, for walker walk environment in hard settings, I get the results about 380. For train settings, I get the results about 750. If we look at the paper https://arxiv.org/pdf/2209.09203.pdf in Table 2 (page 9), the results must be much much higher.
I know those papers work on DMC-GB from Hansen (you also mentioned in the paper), but I don't see the major difference in both the environments from the eval videos (especially for DMC case). Can you please try to replicate and see if you get the same results, or can you explain what creates the difference.
If you need log files or any further explanation, please let me know.

**Comment by vedantdave97** [comment]
I again tested PIEG for walker walk environment. It gets around 540 for evaluation on hard video. It is a bit lower but comparable as per its paper (which mentions around 600).

**Comment by gemcollector** [comment]
hi, there! I uploaded some trained SGQN models, you can evaluate these models on your machine. https://drive.google.com/drive/folders/1QrwzkFPYGi5gxKUfCZHN5A8Z0LTfKLqd?usp=drive_link  I can obtain approximately ~650 scores on average in walker-walk in my Tesla A40 machine. SGQN  is a little bit sensitive to the hyper-parameters. So when I unify this framework, I adjust the hyper-parameters for about a month.  In terms of PIE-G, have you changed the feature_dim to 256 as I mentioned in the Appendix? I think if you run more seeds, the average performance will be close to 600. By the way, I run the SGQN also with 25 feature dims, you can check whether it can achieve better performance. Feel free to ask me if you have further questions!

**Comment by gemcollector** [comment]
I have trained another 2 seeds for SGQN. You can check the results here: https://drive.google.com/file/d/1gvEBWhEli_emXwSTKSpXsVn7-ENRCFFa/view?usp=drive_link. All the hyper-parameters are listed in `config.yaml`, and the log files are contained as well.  The generalization results are also around 650 scores.

**Comment by lucy6201** [comment]
Hello @gemcollector 
In my case as well, I observed that SGQN tends to reproduce with some differences in the robosuite environment compared to the evaluation_score.xlsx. To investigate this, I checked the config.yaml through the provided Google Drive link. I understand that this config is for the DMC environment, but I am wondering if setting nstep to 1 is correct. Referring to Table 2 in the paper, it states that nstep is set to 3 for all algorithms except Dr-Q. Which one is actually correct?

**Comment by gemcollector** [comment]
I should clarify that the n-step I used was set to 3, for robosuite. For your reference, I’ve also uploaded all the results I previously obtained with sgqn here:
https://drive.google.com/file/d/1tWIuDzTalJlH-i4ld2cVFvyreIUtndiE/view?usp=sharing

It has been a while, so I may have forgotten some details, but I did my best to help you reproduce the results. I think a good first step would be to check whether the rendered images match those from the original scene.

**Comment by lucy6201** [comment]
Hi, thank you again for your previous explanations. I have a follow-up question about the DMC video settings. 

If objects_color, table_texture, light_position, light_color, moving_light, and cam_pos are all kept as original, would it be correct to say that RL-ViGen's video easy / video hard are effectively the same experimental settings as DMC-GB's video_easy / video_hard? 

From the code, my current understanding is that the major remaining difference is the chroma-keying implementation, but I am not sure whether there are any other practical differences that would affect the benchmark behavior. 

I would really appreciate your clarification. Thanks!
