### ISSUE TITLE
Missing evaluation scores on Robosuite with cross embodiments settings

### ISSUE THREAD

**Issue by qqqqqqqqqqh** [gemcollector/RL-ViGen#15]
Hello, @gemcollector,
I have noticed that you have loaded the evaluation scores of most experiments. However, the detailed evaluation scores on Robosuite with cross embodiments settings are not provded, specifically in Figure 9. Could you upload the missing results, please?

**Comment by qqqqqqqqqqh** [comment]
I just found the detailed evaluation scores in Figure 8 are also not provided. Could you please upload these as well? I want to compare my method with these algorithms. 👀

**Comment by gemcollector** [comment]
Hi there,  I will upload the results in Figure 8 and Figure 9 this week. Please keep checking our repo, thanks!

**Comment by gemcollector** [comment]
Hi, I have updated the results. You can check the new results file :)

**Comment by qqqqqqqqqqh** [comment]
Thank you very much!
