### ISSUE TITLE
About the scale of images

### ISSUE THREAD

**Issue by yingchengyang** [gemcollector/RL-ViGen#16]
Thanks a lot for your wonderful work! I'm curious about the scale of image inputs in the robosuite. Do we directly input the image within [0, 255]? Or is it necessary to rescale it into [0, 1]? Thanks a lot!

**Comment by gemcollector** [comment]
Hi, there! We will rescale the image during the network forward process. :)

**Comment by yingchengyang** [comment]
Thanks a lot! I have found it.
