### ISSUE TITLE
programs are killed by Dataloader worker

### ISSUE THREAD

**Issue by yingchengyang** [gemcollector/RL-ViGen#17]
Thanks a lot for the wonderful work! When I run the code with the task in the robosuite, sometimes the code will be killed with the Error information like 

```
RuntimeError: DataLoader worker (pid 22358) is killed by signal: Killed.
```

It seems that the problem is because of the workers in Dataloader. Unfortunately, I still have this problem when I set replay_buffer_num_workers=1. Have you met this problem? Thanks a lot again!

**Comment by gemcollector** [comment]
Hi, there! I rarely encounter this issue; it could be due to having too many processes running, which results in insufficient memory or excessive CPU usage.

**Comment by yingchengyang** [comment]
Thanks a lot! I have found that it is because the memory usage is increasing during the training.

**Comment by yingchengyang** [comment]
None, but I find that the code will cause memory leaks with the timestep increasing, which may be the reason for this error. Thus you should carefully check the memory usage. In my experience, 2000 episodes will occupy 60G of memory.

**Comment by yingchengyang** [comment]
Another method is to find out where the memory leak occurred. In my opinion, it is because of the environment itself or the wrapper. So maybe you can reset the environment for every fixed episode. But this will impact the randomness of the environment.
