### ISSUE TITLE
Questions Regarding the Adroit Testing Environment

### ISSUE THREAD

**Issue by xiaobanni** [gemcollector/RL-ViGen#2]
I successfully trained the vrl3 model, but I have some questions during testing.
I discovered that during testing with mode `video-hard`, the agent's actual input is the observation obtained from `observation = time_step.observation`, as shown below:

![image](https://github.com/gemcollector/RL-ViGen/assets/33119031/ed30648a-8a5d-4650-bb98-ab072b610836)

However, neither of the two video recording functions returns something corresponding to the above image:

1: In the `record_gif` function, what's actually recorded is the image of size `(224, 224, 3)` rendered by `self.eval_env._env._env.env.sim.render`. The image and final video are as follows:

![image](https://github.com/gemcollector/RL-ViGen/assets/33119031/58c204b3-32e2-468f-b2fa-cf5246c58edc)
![vrl3](https://github.com/gemcollector/RL-ViGen/assets/33119031/05de1e5e-383f-4723-8358-1dc293fab0c1)

2: In `self.video_recorder.record(self.eval_env)`, what's recorded is the image of size `(224, 224, 3)` returned by `env.render()`. The image and final video are as follows (these are also the images provided in the paper and on the website):

![image](https://github.com/gemcollector/RL-ViGen/assets/33119031/ebc87a8a-be55-431b-ba26-1648525a2bab)

https://github.com/gemcollector/RL-ViGen/assets/33119031/05152b05-e401-4291-8c3b-17cf4afb188a

I would like to know why the images presented in the paper and on the website are not those of the agent's actual testing, or what do these two videos mean separately?
Thank you for adding new environments to the visual reinforcement learning generalization. I look forward to your response.

**Comment by gemcollector** [comment]
Hi, there. Each level of difficulty incorporates multiple textures and video backgrounds for making the test scenarios more diverse. Meanwhile, in the website, as the rendering code shows, we`vil-camera` for rendering. In our experiments, the door and hammer are rendered with `top`, while the pen utilizes `vil-camera` for training. This is consistent with the configuration used in other papers dealing with the adroit task (like RRL, VRL3 etc.). Additionally, as a benchmark paper, you have the flexibility to adjust the camera according to your own training needs.

**Comment by gemcollector** [comment]
You can use the `record_video_gif` function in `eval_adroit.py` to satisfy your need.
