### ISSUE TITLE
Question about resnet encoder

### ISSUE THREAD

**Issue by zichunxx** [gemcollector/RL-ViGen#22]
Hi zhecheng! 

I intended to ask you this question via WeChat, but this will prevent you from answering the same questions repeatly.

For the following code, 

https://github.com/gemcollector/RL-ViGen/blob/e68f622ff1edaf0e2f21fb2620de8e5730f34d6b/algos/pieg.py#L112-L116

Why does the feature map have to be substrated in the `timestep` dimension?

Can't I just keep the feature map directly after convolution?

Best,

Zichun

**Comment by gemcollector** [comment]
Hi, zichu! Great question! You can refer to this issue to find the answer. https://github.com/gemcollector/PIE-G/issues/3
