### ISSUE TITLE
how to change the task and robot in  robosuite?

### ISSUE THREAD

**Issue by zlm200** [gemcollector/RL-ViGen#23]
Hello, this is an exciting job, and your work is very valuable. I am currently looking to change the robot and task in the robosuite experiment. Could you please tell me what modifications I need to make?

**Comment by gemcollector** [comment]
Hi, there. We provide three tasks for changing the visual generalization: `Door`, `Lift`, 'TwoArmPegInHole'. There are two ways for you to change the task: 1. You can directly change the `task_name`, and `env` in `train.sh`. 2. Or you can do some detailed modifications in `envs/robosuiteVGB/cfg/robo_config.yaml`.

**Comment by zlm200** [comment]
OKay, thank you.
