### ISSUE TITLE
Can't download the demo file of adroit

### ISSUE THREAD

**Issue by WinterPenguin2** [gemcollector/RL-ViGen#24]
Hello,

I am currently attempting to run a model in your Adroit environment, and for this purpose, I need to download the demo files. However, I am unable to access the Google Drive link where the demo files are located. Could you kindly guide me on how to obtain the demo files? Alternatively, is there a way to run the model without the demo files? I am planning to run the SAM-G model.

Thank you in advance for your assistance.

**Comment by gemcollector** [comment]
Hi there, we provide a new link here:
https://drive.google.com/drive/folders/1o1l5RHvxV8cGxDYoiIBIshb0csptHOKn?usp=sharing
Our original data and link is from the VRL3 repo: https://github.com/microsoft/VRL3?tab=readme-ov-file
This link is expired. I re-upload the data here.
