### ISSUE TITLE
Running CARLA without rendering

### ISSUE THREAD

**Issue by lee15253** [gemcollector/RL-ViGen#3]
Thank you for your nice benchmark.

Is it possible to run CARLA without a display? I want to run CARLA on a GPU server, but I encounter the following error.

<img width="1552" alt="스크린샷 2023-08-23 오후 4 37 14" src="https://github.com/gemcollector/RL-ViGen/assets/37667392/c1ebf46b-5e11-4166-aaff-3c21bd022ba5">

Is there something I might have missed?

**Comment by lee15253** [comment]
To solve the ld.so error, I changed the LD_PRELOAD in carlatrain.sh from libffi.so.7 to libffi.so.6.
"LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libffi.so.6"

Now the ld.so error does not appear, but I still get a 'time-out runtimeerror' as shown in the picture.

**Comment by gemcollector** [comment]
Hi there! Have you changed the params: `port` and `traffic_port`? They should be aligned with the port you launching the CARLA.

**Comment by lee15253** [comment]
Thank you. It was indeed a port issue.

I have another question, is it impossible to use 'save_video=True' in CARLA on a server (without rendering)? If it's possible, what additional steps do I need to take?

<img width="429" alt="image" src="https://github.com/gemcollector/RL-ViGen/assets/37667392/36d0d3dd-469f-48d5-8870-bdaf11cff874">

**Comment by gemcollector** [comment]
Since the CARLA engine is based on Unreal Engine, we recommend you to render the images with a monitor. You can set the `render_display` param to 1 to render the images.  If you want to render in a headless situation, we recommend using imageio or other functions to save the image and generate the corresponding video or gif.

**Comment by lee15253** [comment]
Thank you.
