### ISSUE TITLE
SVEA implementation

### ISSUE THREAD

**Issue by lee15253** [gemcollector/RL-ViGen#4]
Is SVEA in this repo based on Drq-v2?
So, does that mean, Drq(v1) is the only SAC_based algorithm among the baselines?

**Comment by gemcollector** [comment]
Since DrQ-v2 is a better and more efficient algorithm, we re-implement most of the algorithms under the DDPG-based framework.

**Comment by lee15253** [comment]
Thank you for your prompt answer.
