### ISSUE TITLE
Question about Carla environment config

### ISSUE THREAD

**Issue by lee15253** [gemcollector/RL-ViGen#5]
In appendix d.1.2,
"The Easy level includes soft_noisy_low_light and soft_high_light, while the Medium level is defined by the HardRainSunset and SoftRainSunset conditions. The Hard level contains hard_low_light and hard_noisy_low_light."

Q1. For the easy level, the weather is 'soft_noisy_low_light'. However, when setting the weather in carlaenv10_eval_config.yaml to "soft_noisy_low_light', the following error occurs. 
![image](https://github.com/gemcollector/RL-ViGen/assets/37667392/cf788b5c-420c-4dcc-8e97-d459d4e4b2d4)
I think I might need to change the weather: soft_noisy_low_light in cfgs/setting/setting.yaml to custom_soft_noisy_low_light. Is this correct? That is,

- easy
  - cfgs/setting.setting.yaml 
    - soft_noisy_low_light -> custom_soft_noisy_low_light
    - soft_high_light -> custom_soft_high_light
- medium
  - HardRainSunset , SoftRainSunset (currently working well)
- hard
  - cfgs/setting.setting.yaml 
    - hard_low_light-> custom_hard_low_light
    - hard_noisy_low_light -> custom_hard_noisy_low_light

Q2. There are two weathers each for Easy, Medium, and Hard levels. So, for something like the Score in Figure 4, do you evaluate each difficulty with num_eval_episode for both environments (e.g., HardRainSunset and SoftRainSunset for Medium) and then display the average score of the two weathers?

![image](https://github.com/gemcollector/RL-ViGen/assets/37667392/f5c89b34-68cd-48a5-8dcc-5fd1a851e20e)

**Comment by gemcollector** [comment]
Q1: We apologize for the bug. We encountered some issues while cleaning the code. It has been fixed now, and we appreciate your feedback.

Q2: Yes, we have averaged the results for each weather condition under each difficulty level.

**Comment by lee15253** [comment]
Thank you.
