### ISSUE TITLE
Error for no agent in locodmc_eval

### ISSUE THREAD

**Issue by vedantdave97** [gemcollector/RL-ViGen#9]
https://github.com/gemcollector/RL-ViGen/blob/0158cec6d0105856b5aff8021d9de6ba53c707ac/locodmc_eval.py#L52

This throws error as there is no agent variable defined.
Instead, this should be:
```
agent = torch.load('%s/snapshot.pt' % (work_dir), map_location='cuda:0')
self.agent = agent['agent']
self._global_step = agent['_global_step']
 ```
Btw, great work!

**Comment by gemcollector** [comment]
Hi there! Thank you for pointing out the bug! You're right, I didn't format it to match the one in `eval.py`. Appreciate the reminder! I have pushed a new version.

**Comment by vedantdave97** [comment]
Thanks for the update. I'll check it out and see if it works.

**Comment by vedantdave97** [comment]
Works perfectly. Thanks for the update.
